# Utilizar la imagen oficial de Node.js
FROM node:18
# set the working directory
WORKDIR /app
# Copy the working directory in the container
COPY package*.json /app/

# Install the project dependencies
RUN npm install
# Copy the rest of the project files to the container
COPY . .
# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 8000
# Build the Vue.js application to the production mode to dist folder
